name: VNaStar CI/CD Pipeline - Smart Link Shortener

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  node-build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install Dependencies
      run: npm install

    - name: Run Type Check & Lint
      run: npm run lint

    - name: Build Project
      run: npm run build

